import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  ClipboardCheck,
  FileCheck2,
  FileText,
  GraduationCap,
  HeartPulse,
  Home,
  Info,
  Landmark,
  LifeBuoy,
  ListChecks,
  LockKeyhole,
  Menu,
  MoreHorizontal,
  Search,
  SlidersHorizontal,
  ShieldCheck,
  Sparkles,
  Upload,
  UserRound,
  UsersRound,
  WalletCards,
  X,
  type LucideIcon
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  graduation: GraduationCap,
  home: Home,
  book: BookOpen,
  wallet: WalletCards,
  heart: HeartPulse,
  users: UsersRound,
  briefcase: BriefcaseBusiness,
  family: UsersRound
};

export {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  ClipboardCheck,
  FileCheck2,
  FileText,
  Info,
  Landmark,
  LifeBuoy,
  ListChecks,
  LockKeyhole,
  Menu,
  MoreHorizontal,
  Search,
  SlidersHorizontal,
  ShieldCheck,
  Sparkles,
  Upload,
  UserRound,
  X
};